import { SideMenuModel } from '../model/side-menu.model';

/** Side Menu Items to be as options for display */
export const SIDE_MENU_ITEMS = [
  new SideMenuModel('Events', 'calendar', true, true),
  new SideMenuModel('People', 'people', true, true),
  new SideMenuModel('Risk', 'medical-outline', true, true),
  new SideMenuModel('Settings', 'settings', true, true),
];

/** Help page content to be used on all help pages and for the app guide description */
export const HELP_PAGE_CONTENT = {
  HOME:
    "<p>The key objectives in the job role are shown at top individual tiles represent the <i>Critical Success Factors</i>." +
    " Mostly counts down to  make for better performance.</p> <p>The page is fully configurable through Settings so user can have" +
    " what's most important to them.</p>",
  PIPELINE:
    "<p>Each policy in pipeline can be expanded to see detail. If the user spots <i>Something Wrong</i> they can report it" +
    " (gets logged on Notices).</p> <p>Swipe left to select <i>Next Best Action</i> -" +
    " includes pre-formatted emails based on experience (uses Machine Learning).</p>",
  COMPLAINTS:
    "<p>Each case in complaints can be expanded to see detail. If the user spots <i>Something Wrong</i> they can report it" +
    " (gets logged on Notices).</p> <p>Swipe left to select <i>Next Best Action</i> -" +
    " includes pre-formatted emails based on experience (uses Machine Learning)</p>",
  PENDING_TRANSACTIONS:
    "<p>This is primarily to illustrate graphical reporting capabilities are in the app.</p>" +
    "<p> There is currently just some display options deployed.</p> <p>Future iterations of the app will involve greater" +
    " drill down and links to <i>Next Best Actions</i>.</p>",
  SHORT_TERM_CONTRACTS:
    "<p>This is primarily to illustrate graphical reporting capabilities are in the app.</p>" +
    "<p> There is currently just some display options deployed.</p> <p>Future iterations of the app will involve greater" +
    " drill down and links to <i>Next Best Actions</i>.</p>",
  ADVISERS:
    "<p>The app supports a 5-level agency hierarchy and can integrate to CRMs.</p>" +
    "<p>The user can report where there is <i>Something Wrong</i> (which will be logged in Notices).</p>",
  INSIGHTS:
    "<p>Insights are generated by the Ai Engine searching for where there is most value to be had or where business is" +
    " threatened.</p> <p>Click the Insight for more description (in the next release there will be drill down to data" +
    " behind the Insight in graphical form).</p> <p>Swipe left/right for actions..." +
    " which the Ai Engine will learn from and improve <i>accuracy</i>.</p>",
  NOTICES:
    "<p>Notices are logged from elsewhere in the app.</p> <p>It is the user's route to notifying head office (or elsewhere) where" +
    " there are data issues or other concerns relating to specific cases or advisers.</p>",
  SETTINGS:
    "<p>Settings mainly covers the areas of the app that the user can configure for themselves.</p>" +
    "<p><i>Home screen</i> - the elements and tiles on the dashboard can be chosen by the user <i>" +
    " (i.e. what's most important to them)</i>.</p>" +
    "<p><i>Insight ranking</i> - determines the priority order of insight categories.",
  FILTER:
    "<p>This option can be accessed from swiping from the right side on any screen, selecting Filter at top or bottom of" +
    " screen or from the main menu.</p> <p>Filter ON at top of screen means all data is being viewed with the filter active.</p>",
  MENU: "<p>Items that are <i>check boxed</i> appear in the bottom bar.</p>",
  PROFILE: "<p>Profile settings are typical as found in other apps.</p>",
  SEARCH_PEOPLE: "<p>Search and listing for any party (people).</p",
  SEARCH_POLICY: "<p>Search and listing for policies.</p",
  FEEDBACK:
    "<p>We would like to hear from you.</p> <p>Please use this page to give us feedback about the app.</p",
  CLAIMS:
    "<p>We would like to hear from you.</p> <p>Please use this page to give us feedback about the app.</p",
  CANCELLATIONS:
    "<p>We would like to hear from you.</p> <p>Please use this page to give us feedback about the app.</p",
  ARREARS:
    "<p>We would like to hear from you.</p> <p>Please use this page to give us feedback about the app.</p",
  CUSTOMERS:
    "<p>We would like to hear from you.</p> <p>Please use this page to give us feedback about the app.</p",
  PRODUCTS:
    "<p>We would like to hear from you.</p> <p>Please use this page to give us feedback about the app.</p"
};