export enum InsightCategoryEnum {
    CATEGORY_APP_AWAIT_MONEY = 'CATEGORY_APP_AWAIT_MONEY',
    CATEGORY_APP_AWAIT_EXT_CHECK = 'CATEGORY_APP_AWAIT_EXT_CHECK',
    CATEGORY_DIRTY_APP = 'CATEGORY_DIRTY_APP',
    CATEGORY_APP_AWAIT_COOLOFF = 'CATEGORY_APP_AWAIT_COOLOFF',
    CATEGORY_COMPLAINT = 'CATEGORY_COMPLAINT',
    CATEGORY_CANCEL_NPW = 'CATEGORY_CANCEL_NPW',
    CATEGORY_SWITCH_ACTIVITY = 'CATEGORY_SWITCH_ACTIVITY',
    CATEGORY_ST_CONTRACT_MATURING = 'CATEGORY_ST_CONTRACT_MATURING',
    CATEGORY_VALUATION_ENQUIRIES = 'CATEGORY_VALUATION_ENQUIRIES',
}
